name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  # add: lighthouse(?), a11y

  # lints code
  # Lint:
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run linting
  #       run: npm run lint

  # checks that there are no type errors
  # Typecheck:
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Check types
  #       run: npm run typecheck

  # runs all jest tests
  # Tests:
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run tests
  #       run: npm run test:coverage

  # attempts to build the site
  Lighthouse:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build site
        run: npm run build
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          configPath: './.github/workflows/lighthouserc.json'
